version: '3.8'
services:
  mysql:
    profiles:
      - all
      - db
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: earthly
      MYSQL_USER: earthly
      MYSQL_PASSWORD: earthly
      MYSQL_ROOT_PASSWORD: earthly
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  mysql-test:
    profiles:
      - all
      - db
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: earthly
      MYSQL_USER: earthly
      MYSQL_PASSWORD: earthly
      MYSQL_ROOT_PASSWORD: earthly
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
  redis:
    profiles:
      - all
      - db
    build: ./docker/redis
    restart: always
    ports:
      - "6379:6379"
    tmpfs:
      - /data
  localstack:
    profiles:
      - all
      - localstack
    build: ./docker/localstack
    restart: always
    ports:
      - "4566:4566"
    volumes:
      - ./docker/localstack:/docker-entrypoint-initaws.d # 初回起動スクリプト
      - /var/run/docker.sock:/var/run/docker.sock # おまじない
      - 'localstack-data:/tmp/localstack' # データのマウント
    environment:
      - SERVICES=s3,ses
      - AWS_ACCESS_KEY_ID=earthly
      - AWS_SECRET_ACCESS_KEY=earthly
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1

volumes:
  localstack-data:
    driver: 'local'