version: '3.8'
services:
  mysql:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: earthly
      MYSQL_USER: earthly
      MYSQL_PASSWORD: earthly
      MYSQL_ROOT_PASSWORD: earthly
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  redis:
    build: ./docker/redis
    restart: always
    ports:
      - "6379:6379"
    tmpfs:
      - /data
