server:
  port: 8081
  servlet:
    context-path: /earthly

logging:
  level:
    root: debug

spring:
  datasource:
    url: ${earthly.datasource.url}
    name: ${earthly.datasource.name}
    password: ${earthly.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.name}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      schema: ${earthly.datasource.schema}
      connection-test-query: SELECT 1
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.name}
    password: ${spring.datasource.password}
    schemas: ${earthly.datasource.schema}
    driver-class-name: ${spring.datasource.driver-class-name}
    table: earthly_version
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  security:
    oauth2:
      client:
        provider:
          earthly:
            authorization-uri: ${earthly.oauth2.provider.earthly.base-path}/oauth2/authorize
            token-uri: ${earthly.oauth2.provider.earthly.base-path}/oauth2/token
            user-info-authentication-method: client_secret_post
            user-info-uri: ${earthly.oauth2.provider.earthly.base-path}/userinfo
            jwk-set-uri: ${earthly.oauth2.provider.earthly.base-path}/keys
        #            issuer-uri: ${earthly.oauth2.provider.earthly.base-path}
        registration:
          earthly:
            authorization-grant-type: authorization_code
            client-name: mars
            client-id: 34a10a88cbc2cfab10f4262e09439efec7e76a34e1b28687f0a19d43d3e76f4d
            client-secret: c103fb40ee6d955024b7319b29fc4ad44e8c4c4a3c160b6a6075c00b39bd1991
            provider: earthly
            client-authentication-method: client_secret_post
            redirect-uri: http://127.0.0.1:${server.port}${server.servlet.context-path}/login/oauth2/code
            scope:
              - openid

management:
  server:
    port: 9090

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true


earthly:
  datasource:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    name: ${MYSQL_USER_NAME:earthly}
    password: ${MYSQL_PASSWORD:earthly}
    schema: ${MYSQL_SCHEMA:earthly}
    url: jdbc:mysql://${earthly.datasource.host}:${earthly.datasource.port}/${earthly.datasource.schema}?allowPublicKeyRetrieval=true&useSSL=false
  oauth2:
    provider:
      earthly:
        base-path: http://localhost:9000/earthly

aws:
  ses:
    from: noreply@example.com
    region: ap-northeast-1
