server:
  port: 9000
  servlet:
    context-path: /earthly

logging:
  level:
    root: debug

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ${auth.datasource.name}
    password: ${auth.datasource.password}
    url: ${auth.datasource.url}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      jdbc-url: ${auth.datasource.url}
      username: ${auth.datasource.name}
      password: ${auth.datasource.password}
  docker:
    compose:
      enabled: true
      profiles:
        active: all
      lifecycle-management: start_only
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    user: ${auth.datasource.name}
    password: ${auth.datasource.password}
    url: ${auth.datasource.url}
    schemas: ${auth.datasource.schema}
    table: earthly_version
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  data:
    redis:
      host: ${auth.redis.host}
      port: ${auth.redis.port}
      connect-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health, quickTEST, fullTEST, awesomeTEST
      base-path: /
  endpoint:
    health:
      show-details: always

doma:
  dialect: mysql

auth:
  host: localhost
  version: "@version@"
  datasource:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    name: ${MYSQL_USER_NAME:earthly}
    password: ${MYSQL_USER_PASSWORD:earthly}
    schema: ${MYSQL_SCHEMA:earthly}
    url: jdbc:mysql://${auth.datasource.host}:${auth.datasource.port}/${auth.datasource.schema}?allowPublicKeyRetrieval=true&useSSL=false
  security:
    authorization:
      issuer: http://${auth.host}:${server.port}${server.servlet.context-path}
      token:
        expire: 28800 # 秒指定
  redis:
    host: localhost
    port: 6379

aws:
  ses:
    from: noreply@example.com
    region: ap-northeast-1