server:
  servlet:
    context-path: /earthly
  port: 8080

logging:
  level:
    root: debug

spring:
  profiles:
    active: local
  datasource:
    url: ${earthly.datasource.url}
    name: ${earthly.datasource.name}
    password: ${earthly.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.name}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      schema: ${earthly.datasource.schema}
      connection-test-query: SELECT 1
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.name}
    password: ${spring.datasource.password}
    schemas: ${earthly.datasource.schema}
    driver-class-name: ${spring.datasource.driver-class-name}
    table: earthly_version
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  data:
    redis:
      host: ${earthly.redis.host}
      port: ${earthly.redis.port}
      connect-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,quickTEST
      base-path: /

earthly:
  base-url: http://localhost:${server.port}${server.servlet.context-path}
  datasource:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    name: ${MYSQL_USER_NAME:earthly}
    password: ${MYSQL_PASSWORD:earthly}
    schema: ${MYSQL_SCHEMA:earthly}
    url: jdbc:mysql://${earthly.datasource.host}:${earthly.datasource.port}/${earthly.datasource.schema}?allowPublicKeyRetrieval=true&useSSL=false
  oauth2:
    provider:
      earthly:
        base-path: http://localhost:9000/earthly
  redis:
    host: localhost
    port: 6379

aws:
  provider:
    service: local
    region: ap-northeast-1
    endpoint: http://localhost:4566 # docker-compose.ymlのlocalstackに記載している内容に合わせてください。
  ses:
    from: noreply@planet-system.co.jp
    region: ${aws.provider.region}
