-- Generated By Doma Tools
SELECT
  /*%expand "organization, company, country"*/*
FROM
  organization
  LEFT OUTER JOIN company ON organization.company_id = company.id
  LEFT OUTER JOIN country ON company.country_id = country.id
WHERE
  organization.id = /*id*/'a'
  /*%if !hasViewAllCompany*/
  AND organization.company_id (
    SELECT
      management_company_user.company_id
    FROM
      management_company_user
    WHERE
      management_company_user.user_id = /*operatorUserId*/'a'
    UNION ALL
    SELECT
      user.company_id
    FROM
      user
    WHERE
      user.id = /*operatorUserId*/'a'
      AND user.is_deleted = 0
  )
  /*%end*/
  AND organization.is_deleted = 0