-- Generated By Doma Tools
SELECT
  /*%expand "organization, company, country"*/*
FROM
  organization
  LEFT OUTER JOIN company ON organization.company_id = company.id
  LEFT OUTER JOIN country ON company.country_id = country.id
WHERE
  organization.company_id = /*companyId*/''
  /*%if @isNotBlank(name)*/
    AND organization.name LIKE /*@infix(name)*/''
  /*%end*/
  AND organization.is_deleted = 0
ORDER BY
  organization.name,
  organization.id