name: CI

on:
  push:
    branches:
      - main
      - develop
      - issue/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: docker setup db
        run: docker-compose --profile all up -d
      - name: test & verify
        run: |
          chmod +x gradlew
          ./gradlew :repository:flywayMigrate
          ./gradlew check --info
#      - name: upload report
#        if: always()
#        with:
#          name: test result
#          path: build/test-results/test
