name: CI

on:
  push:
    branches:
      - main
      - develop
      - issue/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: docker setup db
        run: docker-compose --profile all up -d
      - name: test & verify
        run: |
          chmod +x gradlew
          ./gradlew :repository:flywayMigrate
          ./gradlew check --info
      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: report.xml
          paths: |
            ${{ github.workspace }}/repository/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/webapp/build/reports/jacoco/test/jacocoTestReport.xml
      - name: JaCoCo Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: |
            ${{ github.workspace }}/repository/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/webapp/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
